"""
Strongly-typed event contracts for task and workflow lifecycle.

These events are used with Inngest for orchestrating task execution.
Each contract defines both the event name and payload schema.

Usage:
    # Sending an event:
    await inngest_client.send(
        inngest.Event(
            name=TaskReadyEvent.name,
            data=TaskReadyEvent(run_id=..., task_id=...).model_dump(),
        )
    )

    # Receiving an event (in Inngest function):
    event = TaskReadyEvent(**ctx.event.data)
"""

from typing import ClassVar
from uuid import UUID

from pydantic import model_validator

from h_arcane.core._internal.events.base import InngestEventContract


# =============================================================================
# Task Lifecycle Events
# =============================================================================


class TaskReadyEvent(InngestEventContract):
    """
    Emitted when a task's dependencies are satisfied and it's ready to execute.

    Triggers: task_execute Inngest function
    """

    name: ClassVar[str] = "task/ready"

    run_id: UUID
    experiment_id: UUID
    task_id: UUID


class TaskStartedEvent(InngestEventContract):
    """
    Emitted when task execution begins.

    For observability/logging - not currently used as a trigger.
    """

    name: ClassVar[str] = "task/started"

    run_id: UUID
    experiment_id: UUID
    task_id: UUID
    execution_id: UUID


class TaskCompletedEvent(InngestEventContract):
    """
    Emitted when a task completes successfully.

    Triggers: task_propagate Inngest function
    """

    name: ClassVar[str] = "task/completed"

    run_id: UUID
    experiment_id: UUID
    task_id: UUID
    execution_id: UUID


class TaskFailedEvent(InngestEventContract):
    """
    Emitted when a task fails.

    Triggers: task_failure_propagate (to check if workflow should fail)
    """

    name: ClassVar[str] = "task/failed"

    run_id: UUID
    experiment_id: UUID
    task_id: UUID
    execution_id: UUID
    error: str


# =============================================================================
# Workflow Lifecycle Events
# =============================================================================


class WorkflowStartedEvent(InngestEventContract):
    """
    Emitted to start workflow execution.

    Triggers: workflow_start Inngest function
    """

    name: ClassVar[str] = "workflow/started"

    run_id: UUID
    experiment_id: UUID


class WorkflowCompletedEvent(InngestEventContract):
    """
    Emitted when all tasks in a workflow complete successfully.

    Triggers: workflow_complete Inngest function
    """

    name: ClassVar[str] = "workflow/completed"

    run_id: UUID
    experiment_id: UUID


class WorkflowFailedEvent(InngestEventContract):
    """
    Emitted when a workflow fails (unrecoverable error or task failure).

    Triggers: workflow_failed Inngest function
    """

    name: ClassVar[str] = "workflow/failed"

    run_id: UUID
    experiment_id: UUID
    error: str


# =============================================================================
# Benchmark CLI Events
# =============================================================================


class BenchmarkRunRequest(InngestEventContract):
    """
    Request to start a benchmark run from CLI.

    Emitted by CLI with serializable data. The server-side Inngest function
    reconstructs the worker and workflow, then triggers the standard workflow
    execution flow.

    Triggers: benchmark_run_start Inngest function
    """

    name: ClassVar[str] = "benchmark/run-request"

    request_id: str  # UUID generated by CLI to track the run
    cohort_name: str
    benchmark_name: str  # e.g., "smoke_test", "gdpeval"
    workflow_name: str | None = None  # e.g., "single", "linear", "parallel"
    experiment_id: UUID | None = None
    model: str  # e.g., "gpt-4o-mini"
    timeout_seconds: int  # CLI timeout for polling
    max_questions: int = 10

    @model_validator(mode="after")
    def validate_launch_target(self) -> "BenchmarkRunRequest":
        """Require exactly one launch target: workflow factory or seeded experiment."""
        has_workflow = self.workflow_name is not None
        has_experiment = self.experiment_id is not None
        if has_workflow == has_experiment:
            raise ValueError("BenchmarkRunRequest requires exactly one of workflow_name or experiment_id")
        return self
