"""E2E integration test for the researchrubrics pipeline (offline, no real E2B).

Exercises the full orchestration stack with all externals stubbed:
  - ``ResearchRubricsBenchmark(limit=1)`` supplies real task metadata
  - ``StubWorker`` + manual sandbox writes simulate a researcher that
    produces ``/workspace/final_output/report.md``
  - ``SandboxResourcePublisher`` syncs that file to the RunResource store
  - ``StubCriterion`` + a fake ``CriterionRuntime`` evaluates against the
    published resources (resource blob exists + sandbox readable +
    ``echo $((1+1))`` canary)

This is the fast offline mirror of the online
``tests/e2e/test_benchmarks_stubbed.py`` demo run.
"""

import asyncio
import hashlib
from pathlib import Path
from uuid import uuid4

from ergon_builtins.benchmarks.researchrubrics.benchmark import ResearchRubricsBenchmark
from ergon_builtins.evaluators.criteria.stub_criterion import StubCriterion
from ergon_builtins.workers.baselines.stub_worker import StubWorker
from ergon_core.api import Experiment
from ergon_core.api.criterion_runtime import CommandResult, SandboxResult
from ergon_core.api.evaluation_context import EvaluationContext
from ergon_core.api.results import WorkerOutput
from ergon_core.api.task_types import BenchmarkTask
from ergon_core.core.persistence.shared.db import ensure_db, get_session
from ergon_core.core.persistence.shared.enums import RunStatus, TaskExecutionStatus
from ergon_core.core.persistence.telemetry.models import (
    RunRecord,
    RunResource,
    RunResourceKind,
    RunTaskEvaluation,
    RunTaskExecution,
)
from ergon_core.core.providers.sandbox.resource_publisher import (
    SandboxResourcePublisher,
)
from ergon_core.core.runtime.services.orchestration_dto import (
    FinalizeTaskExecutionCommand,
    FinalizeWorkflowCommand,
    InitializeWorkflowCommand,
    PrepareTaskExecutionCommand,
    PropagateTaskCompletionCommand,
)
from ergon_core.core.runtime.services.run_service import create_run
from ergon_core.core.runtime.services.task_execution_service import (
    TaskExecutionService,
)
from ergon_core.core.runtime.services.task_propagation_service import (
    TaskPropagationService,
)
from ergon_core.core.runtime.services.workflow_finalization_service import (
    WorkflowFinalizationService,
)
from ergon_core.core.runtime.services.workflow_initialization_service import (
    WorkflowInitializationService,
)
from sqlmodel import select

# Canned report body big enough to exercise hashing / blob storage.
STUB_REPORT_CONTENT = """# Findings

Report body produced by the offline stub pipeline for integration
testing.  Not generated by a real LLM.

## Sources

- https://example.test/offline-fixture
"""

# ---------------------------------------------------------------------------
# Fake sandbox + runtime
# ---------------------------------------------------------------------------


class _FakeEntry:
    def __init__(self, *, name: str) -> None:
        self.name = name


class _FakeSandboxFiles:
    def __init__(self) -> None:
        self._files: dict[str, bytes] = {}

    def put(self, path: str, content: bytes) -> None:
        self._files[path] = content

    async def list(self, path: str) -> list[_FakeEntry]:
        prefix = path if path.endswith("/") else path + "/"
        entries: list[_FakeEntry] = []
        seen: set[str] = set()
        for key in self._files:
            if key.startswith(prefix):
                remainder = key[len(prefix) :]
                if "/" not in remainder and remainder not in seen:
                    entries.append(_FakeEntry(name=remainder))
                    seen.add(remainder)
        if not entries:
            raise FileNotFoundError(path)
        return entries

    async def read(self, path: str, *, request_timeout: int = 30) -> bytes:
        if path not in self._files:
            raise FileNotFoundError(path)
        return self._files[path]

    async def write(self, path: str, content: str | bytes) -> None:
        if isinstance(content, str):
            content = content.encode("utf-8")
        self._files[path] = content


class _FakeCommands:
    async def run(self, cmd: str, **kwargs: object) -> object:  # noqa: ARG002
        class _Result:
            exit_code = 0
            stdout = ""
            stderr = ""

        return _Result()


class _FakeSandbox:
    sandbox_id = "fake-sandbox-e2e"

    def __init__(self) -> None:
        self.files = _FakeSandboxFiles()
        self.commands = _FakeCommands()


class _FakeRuntime:
    """Minimal ``CriterionRuntime`` backed by the fake sandbox above."""

    def __init__(self, sandbox: _FakeSandbox) -> None:
        self._sandbox = sandbox

    async def ensure_sandbox(self) -> None:
        return None

    async def upload_files(self, files: list[dict]) -> None:  # noqa: ARG002
        return None

    async def write_file(self, path: str, content: bytes) -> None:
        await self._sandbox.files.write(path, content)

    async def run_command(self, command: str, timeout: int = 30) -> CommandResult:  # noqa: ARG002
        # ``test -r <path>``: succeed iff the fake sandbox has that file.
        if command.startswith("test -r "):
            path = command[len("test -r ") :].strip().strip("'\"")
            exists = path in self._sandbox.files._files
            return CommandResult(stdout="", stderr="", exit_code=0 if exists else 1)
        # ``echo $((1+1))`` canary.
        if command == "echo $((1+1))":
            return CommandResult(stdout="2\n", stderr="", exit_code=0)
        return CommandResult(stdout="", stderr="", exit_code=0)

    async def execute_code(self, code: str) -> SandboxResult:  # noqa: ARG002
        return SandboxResult()

    async def call_llm_judge(self, messages: list, response_type: type):  # noqa: ARG002
        raise NotImplementedError("LLM judge not used in offline stub pipeline")

    async def cleanup(self) -> None:
        return None


# ---------------------------------------------------------------------------
# Test
# ---------------------------------------------------------------------------


def test_researchrubrics_e2e_offline(tmp_path: Path) -> None:
    """Golden-path E2E: benchmark -> worker -> publisher -> StubCriterion."""
    ensure_db()

    # ── Construct ──────────────────────────────────────────────────
    benchmark = ResearchRubricsBenchmark(limit=1)

    # Inline minimal rubric: Rubric(criteria=[StubCriterion()]).  Not
    # importing the registered ``stub-rubric`` evaluator because that
    # would drag in evaluator construction boilerplate; we only need
    # StubCriterion directly.
    worker = StubWorker(name="researcher", model="openai:gpt-4o")

    from ergon_builtins.evaluators.rubrics.stub_rubric import StubRubric

    rubric = StubRubric(name="stub-rubric")

    experiment = Experiment.from_single_worker(
        benchmark=benchmark,
        worker=worker,
        evaluators={"default": rubric},
    )
    experiment.validate()
    persisted = experiment.persist()

    # ── Create Run + Initialize ────────────────────────────────────
    run = create_run(persisted)
    init_svc = WorkflowInitializationService()
    initialized = init_svc.initialize(
        InitializeWorkflowCommand(
            run_id=run.id,
            definition_id=persisted.definition_id,
        )
    )
    assert initialized.total_tasks >= 1

    # ── Execute Tasks (with fake sandbox + publisher) ──────────────
    exec_svc = TaskExecutionService()
    completed_tasks = []

    fake_sandbox = _FakeSandbox()
    blob_root = tmp_path / "blobs"
    blob_root.mkdir()

    for task_desc in initialized.initial_ready_tasks:
        prepared = exec_svc.prepare(
            PrepareTaskExecutionCommand(
                run_id=run.id,
                definition_id=persisted.definition_id,
                task_id=task_desc.task_id,
            )
        )

        # Simulate a researcher that wrote the canned report.
        report_content = STUB_REPORT_CONTENT.encode("utf-8")
        asyncio.run(
            fake_sandbox.files.write(
                "/workspace/final_output/report.md",
                report_content,
            )
        )

        # Run publisher.sync() against the fake sandbox.
        publisher = SandboxResourcePublisher(
            sandbox=fake_sandbox,  # type: ignore[arg-type]
            run_id=run.id,
            task_execution_id=prepared.execution_id,
            blob_root=blob_root,
        )
        created = asyncio.run(publisher.sync())
        assert len(created) >= 1, "Publisher should have created at least one resource"
        assert created[0].kind == RunResourceKind.REPORT

        # Verify content hash.
        expected_hash = hashlib.sha256(report_content).hexdigest()
        assert created[0].content_hash == expected_hash

        # Finalize the task execution.
        exec_svc.finalize_success(
            FinalizeTaskExecutionCommand(
                execution_id=prepared.execution_id,
                output_text="Stub report written",
            )
        )
        completed_tasks.append((task_desc, prepared))

    # ── Propagate ──────────────────────────────────────────────────
    prop_svc = TaskPropagationService()
    for task_desc, prepared in completed_tasks:
        prop_svc.propagate(
            PropagateTaskCompletionCommand(
                run_id=run.id,
                definition_id=persisted.definition_id,
                task_id=task_desc.task_id,
                execution_id=prepared.execution_id,
            )
        )

    # ── Evaluate (in-process criterion with fake runtime) ──────────
    for task_desc, prepared in completed_tasks:
        criterion = StubCriterion()
        ctx = EvaluationContext(
            run_id=run.id,
            task_id=task_desc.task_id,
            execution_id=prepared.execution_id,
            task=BenchmarkTask(
                task_key="researchrubrics-offline-001",
                instance_key="default",
                description="offline integration stub",
            ),
            worker_result=WorkerOutput(output="Stub report written"),
            runtime=_FakeRuntime(fake_sandbox),
        )
        result = asyncio.run(criterion.evaluate(ctx))
        assert result.passed, f"StubCriterion failed: {result.feedback}"
        assert result.score == 1.0

        # Persist evaluation.
        eval_record = RunTaskEvaluation(
            run_id=run.id,
            definition_task_id=task_desc.task_id,
            definition_evaluator_id=uuid4(),
            score=result.score,
            passed=result.passed,
            feedback=result.feedback,
        )
        with get_session() as session:
            session.add(eval_record)
            session.commit()

    # ── Finalize Workflow ──────────────────────────────────────────
    final_svc = WorkflowFinalizationService()
    final_svc.finalize(
        FinalizeWorkflowCommand(
            run_id=run.id,
            definition_id=persisted.definition_id,
        )
    )

    # ── Assert final state ─────────────────────────────────────────
    with get_session() as session:
        final_run = session.get(RunRecord, run.id)
        assert final_run is not None
        assert final_run.status == RunStatus.COMPLETED

        executions = list(
            session.exec(
                select(RunTaskExecution).where(
                    RunTaskExecution.run_id == run.id,
                )
            ).all()
        )
        assert len(executions) >= 1
        for ex in executions:
            assert ex.status == TaskExecutionStatus.COMPLETED

        evaluations = list(
            session.exec(
                select(RunTaskEvaluation).where(
                    RunTaskEvaluation.run_id == run.id,
                )
            ).all()
        )
        assert len(evaluations) >= 1
        for ev in evaluations:
            assert ev.score is not None
            assert ev.passed is True

        # Verify RunResource rows exist.
        resources = list(
            session.exec(select(RunResource).where(RunResource.run_id == run.id)).all()
        )
        assert len(resources) >= 1
        report_resources = [r for r in resources if r.kind == RunResourceKind.REPORT.value]
        assert len(report_resources) >= 1
        assert report_resources[0].content_hash is not None
