"""initial schema v2

Revision ID: 5f01559f2bc3
Revises:
Create Date: 2026-04-14 12:08:00.663894
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "5f01559f2bc3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experiment_cohorts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status", sa.Enum("ACTIVE", "ARCHIVED", name="experimentcohortstatus"), nullable=False
        ),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_experiment_cohorts_name"), "experiment_cohorts", ["name"], unique=True)
    op.create_table(
        "experiment_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("benchmark_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiment_definitions_benchmark_type"),
        "experiment_definitions",
        ["benchmark_type"],
        unique=False,
    )
    op.create_table(
        "saved_benchmark_specs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("benchmark_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_saved_benchmark_specs_benchmark_type"),
        "saved_benchmark_specs",
        ["benchmark_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_saved_benchmark_specs_slug"), "saved_benchmark_specs", ["slug"], unique=True
    )
    op.create_table(
        "saved_evaluator_specs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("evaluator_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_saved_evaluator_specs_evaluator_type"),
        "saved_evaluator_specs",
        ["evaluator_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_saved_evaluator_specs_slug"), "saved_evaluator_specs", ["slug"], unique=True
    )
    op.create_table(
        "saved_experiment_templates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("template_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_saved_experiment_templates_slug"),
        "saved_experiment_templates",
        ["slug"],
        unique=True,
    )
    op.create_table(
        "saved_worker_specs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("worker_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_target", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_saved_worker_specs_slug"), "saved_worker_specs", ["slug"], unique=True)
    op.create_index(
        op.f("ix_saved_worker_specs_worker_type"),
        "saved_worker_specs",
        ["worker_type"],
        unique=False,
    )
    op.create_table(
        "experiment_cohort_stats",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cohort_id", sa.Uuid(), nullable=False),
        sa.Column("total_runs", sa.Integer(), nullable=False),
        sa.Column("completed_runs", sa.Integer(), nullable=False),
        sa.Column("failed_runs", sa.Integer(), nullable=False),
        sa.Column("average_score", sa.Float(), nullable=True),
        sa.Column("best_score", sa.Float(), nullable=True),
        sa.Column("worst_score", sa.Float(), nullable=True),
        sa.Column("average_duration_ms", sa.Integer(), nullable=True),
        sa.Column("failure_rate", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cohort_id"],
            ["experiment_cohorts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiment_cohort_stats_cohort_id"),
        "experiment_cohort_stats",
        ["cohort_id"],
        unique=True,
    )
    op.create_table(
        "experiment_definition_evaluators",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("experiment_definition_id", sa.Uuid(), nullable=False),
        sa.Column("binding_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("evaluator_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("snapshot_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_definition_id"],
            ["experiment_definitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiment_definition_evaluators_binding_key"),
        "experiment_definition_evaluators",
        ["binding_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiment_definition_evaluators_evaluator_type"),
        "experiment_definition_evaluators",
        ["evaluator_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiment_definition_evaluators_experiment_definition_id"),
        "experiment_definition_evaluators",
        ["experiment_definition_id"],
        unique=False,
    )
    op.create_table(
        "experiment_definition_instances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("experiment_definition_id", sa.Uuid(), nullable=False),
        sa.Column("instance_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("benchmark_instance_state", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_definition_id"],
            ["experiment_definitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiment_definition_instances_experiment_definition_id"),
        "experiment_definition_instances",
        ["experiment_definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiment_definition_instances_instance_key"),
        "experiment_definition_instances",
        ["instance_key"],
        unique=False,
    )
    op.create_table(
        "experiment_definition_workers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("experiment_definition_id", sa.Uuid(), nullable=False),
        sa.Column("binding_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("worker_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_target", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("snapshot_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_definition_id"],
            ["experiment_definitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiment_definition_workers_binding_key"),
        "experiment_definition_workers",
        ["binding_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiment_definition_workers_experiment_definition_id"),
        "experiment_definition_workers",
        ["experiment_definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiment_definition_workers_worker_type"),
        "experiment_definition_workers",
        ["worker_type"],
        unique=False,
    )
    op.create_table(
        "rollout_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("definition_id", sa.Uuid(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["definition_id"],
            ["experiment_definitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rollout_batches_definition_id"), "rollout_batches", ["definition_id"], unique=False
    )
    op.create_index(op.f("ix_rollout_batches_status"), "rollout_batches", ["status"], unique=False)
    op.create_table(
        "runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("experiment_definition_id", sa.Uuid(), nullable=False),
        sa.Column("cohort_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "EXECUTING",
                "EVALUATING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="runstatus",
            ),
            nullable=False,
        ),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cohort_id"],
            ["experiment_cohorts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["experiment_definition_id"],
            ["experiment_definitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_runs_cohort_id"), "runs", ["cohort_id"], unique=False)
    op.create_index(
        op.f("ix_runs_experiment_definition_id"), "runs", ["experiment_definition_id"], unique=False
    )
    op.create_index(op.f("ix_runs_status"), "runs", ["status"], unique=False)
    op.create_table(
        "training_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("experiment_definition_id", sa.Uuid(), nullable=False),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("RUNNING", "COMPLETED", "FAILED", name="trainingstatus"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("output_dir", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("total_steps", sa.Integer(), nullable=True),
        sa.Column("final_loss", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_definition_id"],
            ["experiment_definitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_training_sessions_experiment_definition_id"),
        "training_sessions",
        ["experiment_definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_training_sessions_status"), "training_sessions", ["status"], unique=False
    )
    op.create_table(
        "experiment_definition_tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("experiment_definition_id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("task_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parent_task_id", sa.Uuid(), nullable=True),
        sa.Column("task_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("task_payload", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_definition_id"],
            ["experiment_definitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["experiment_definition_instances.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_task_id"],
            ["experiment_definition_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiment_definition_tasks_experiment_definition_id"),
        "experiment_definition_tasks",
        ["experiment_definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiment_definition_tasks_instance_id"),
        "experiment_definition_tasks",
        ["instance_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiment_definition_tasks_task_key"),
        "experiment_definition_tasks",
        ["task_key"],
        unique=False,
    )
    op.create_table(
        "rollout_batch_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["rollout_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rollout_batch_runs_batch_id"), "rollout_batch_runs", ["batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_rollout_batch_runs_run_id"), "rollout_batch_runs", ["run_id"], unique=False
    )
    op.create_table(
        "run_graph_annotations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("target_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("namespace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_annotation_lookup",
        "run_graph_annotations",
        ["run_id", "target_type", "target_id", "namespace", "sequence"],
        unique=False,
    )
    op.create_index(
        op.f("ix_run_graph_annotations_run_id"), "run_graph_annotations", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_run_graph_annotations_sequence"),
        "run_graph_annotations",
        ["sequence"],
        unique=False,
    )
    op.create_table(
        "run_graph_mutations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("mutation_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("actor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("old_value", sa.JSON(), nullable=True),
        sa.Column("new_value", sa.JSON(), nullable=True),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_run_graph_mutations_mutation_type"),
        "run_graph_mutations",
        ["mutation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_run_graph_mutations_run_id"), "run_graph_mutations", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_run_graph_mutations_sequence"), "run_graph_mutations", ["sequence"], unique=False
    )
    op.create_index(
        op.f("ix_run_graph_mutations_target_id"), "run_graph_mutations", ["target_id"], unique=False
    )
    op.create_table(
        "threads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("topic", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_a_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_b_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_threads_agent_a_id"), "threads", ["agent_a_id"], unique=False)
    op.create_index(op.f("ix_threads_agent_b_id"), "threads", ["agent_b_id"], unique=False)
    op.create_index(op.f("ix_threads_run_id"), "threads", ["run_id"], unique=False)
    op.create_table(
        "training_metrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("step", sa.Integer(), nullable=False),
        sa.Column("epoch", sa.Float(), nullable=True),
        sa.Column("loss", sa.Float(), nullable=True),
        sa.Column("grad_norm", sa.Float(), nullable=True),
        sa.Column("learning_rate", sa.Float(), nullable=True),
        sa.Column("reward_mean", sa.Float(), nullable=True),
        sa.Column("reward_std", sa.Float(), nullable=True),
        sa.Column("entropy", sa.Float(), nullable=True),
        sa.Column("completion_mean_length", sa.Float(), nullable=True),
        sa.Column("step_time_s", sa.Float(), nullable=True),
        sa.Column("extra_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_training_metrics_session_id"), "training_metrics", ["session_id"], unique=False
    )
    op.create_table(
        "experiment_definition_task_assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("experiment_definition_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("worker_binding_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("assignment_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_definition_id"],
            ["experiment_definitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["experiment_definition_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiment_definition_task_assignments_experiment_definition_id"),
        "experiment_definition_task_assignments",
        ["experiment_definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiment_definition_task_assignments_task_id"),
        "experiment_definition_task_assignments",
        ["task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiment_definition_task_assignments_worker_binding_key"),
        "experiment_definition_task_assignments",
        ["worker_binding_key"],
        unique=False,
    )
    op.create_table(
        "experiment_definition_task_dependencies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("experiment_definition_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("depends_on_task_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["depends_on_task_id"],
            ["experiment_definition_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["experiment_definition_id"],
            ["experiment_definitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["experiment_definition_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiment_definition_task_dependencies_depends_on_task_id"),
        "experiment_definition_task_dependencies",
        ["depends_on_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiment_definition_task_dependencies_experiment_definition_id"),
        "experiment_definition_task_dependencies",
        ["experiment_definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiment_definition_task_dependencies_task_id"),
        "experiment_definition_task_dependencies",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "experiment_definition_task_evaluators",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("experiment_definition_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("evaluator_binding_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_definition_id"],
            ["experiment_definitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["experiment_definition_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiment_definition_task_evaluators_evaluator_binding_key"),
        "experiment_definition_task_evaluators",
        ["evaluator_binding_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiment_definition_task_evaluators_experiment_definition_id"),
        "experiment_definition_task_evaluators",
        ["experiment_definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiment_definition_task_evaluators_task_id"),
        "experiment_definition_task_evaluators",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "run_graph_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("definition_task_id", sa.Uuid(), nullable=True),
        sa.Column("instance_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("task_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("assigned_worker_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["definition_task_id"],
            ["experiment_definition_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_run_graph_nodes_run_id"), "run_graph_nodes", ["run_id"], unique=False)
    op.create_index(op.f("ix_run_graph_nodes_status"), "run_graph_nodes", ["status"], unique=False)
    op.create_index(
        op.f("ix_run_graph_nodes_task_key"), "run_graph_nodes", ["task_key"], unique=False
    )
    op.create_table(
        "run_task_evaluations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("definition_task_id", sa.Uuid(), nullable=False),
        sa.Column("definition_evaluator_id", sa.Uuid(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column("feedback", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("summary_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["definition_evaluator_id"],
            ["experiment_definition_evaluators.id"],
        ),
        sa.ForeignKeyConstraint(
            ["definition_task_id"],
            ["experiment_definition_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_run_task_evaluations_definition_evaluator_id"),
        "run_task_evaluations",
        ["definition_evaluator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_run_task_evaluations_definition_task_id"),
        "run_task_evaluations",
        ["definition_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_run_task_evaluations_run_id"), "run_task_evaluations", ["run_id"], unique=False
    )
    op.create_table(
        "run_graph_edges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("definition_dependency_id", sa.Uuid(), nullable=True),
        sa.Column("source_node_id", sa.Uuid(), nullable=False),
        sa.Column("target_node_id", sa.Uuid(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["definition_dependency_id"],
            ["experiment_definition_task_dependencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_node_id"],
            ["run_graph_nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_node_id"],
            ["run_graph_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_run_graph_edges_run_id"), "run_graph_edges", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_run_graph_edges_source_node_id"),
        "run_graph_edges",
        ["source_node_id"],
        unique=False,
    )
    op.create_index(op.f("ix_run_graph_edges_status"), "run_graph_edges", ["status"], unique=False)
    op.create_index(
        op.f("ix_run_graph_edges_target_node_id"),
        "run_graph_edges",
        ["target_node_id"],
        unique=False,
    )
    op.create_table(
        "run_task_executions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("definition_task_id", sa.Uuid(), nullable=True),
        sa.Column("definition_worker_id", sa.Uuid(), nullable=True),
        sa.Column("node_id", sa.Uuid(), nullable=True),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "RUNNING", "COMPLETED", "FAILED", "SKIPPED", name="taskexecutionstatus"
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("output_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("output_json", sa.JSON(), nullable=True),
        sa.Column("error_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["definition_task_id"],
            ["experiment_definition_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["definition_worker_id"],
            ["experiment_definition_workers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["run_graph_nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_run_task_executions_definition_task_id"),
        "run_task_executions",
        ["definition_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_run_task_executions_definition_worker_id"),
        "run_task_executions",
        ["definition_worker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_run_task_executions_node_id"), "run_task_executions", ["node_id"], unique=False
    )
    op.create_index(
        op.f("ix_run_task_executions_run_id"), "run_task_executions", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_run_task_executions_status"), "run_task_executions", ["status"], unique=False
    )
    op.create_table(
        "run_actions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("task_execution_id", sa.Uuid(), nullable=False),
        sa.Column("action_num", sa.Integer(), nullable=False),
        sa.Column("action_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("input_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("output_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error_json", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_execution_id"],
            ["run_task_executions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_run_actions_run_id"), "run_actions", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_run_actions_task_execution_id"), "run_actions", ["task_execution_id"], unique=False
    )
    op.create_table(
        "run_generation_turns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("task_execution_id", sa.Uuid(), nullable=False),
        sa.Column("worker_binding_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("turn_index", sa.Integer(), nullable=False),
        sa.Column("prompt_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("raw_response", sa.JSON(), nullable=True),
        sa.Column("response_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tool_calls_json", sa.JSON(), nullable=True),
        sa.Column("tool_results_json", sa.JSON(), nullable=True),
        sa.Column("token_ids_json", sa.JSON(), nullable=True),
        sa.Column("logprobs_json", sa.JSON(), nullable=True),
        sa.Column("policy_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("execution_outcome", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_execution_id"],
            ["run_task_executions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_run_generation_turns_execution_outcome"),
        "run_generation_turns",
        ["execution_outcome"],
        unique=False,
    )
    op.create_index(
        op.f("ix_run_generation_turns_run_id"), "run_generation_turns", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_run_generation_turns_task_execution_id"),
        "run_generation_turns",
        ["task_execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_run_generation_turns_worker_binding_key"),
        "run_generation_turns",
        ["worker_binding_key"],
        unique=False,
    )
    op.create_table(
        "run_resources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("task_execution_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mime_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_execution_id"],
            ["run_task_executions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_run_resources_run_id"), "run_resources", ["run_id"], unique=False)
    op.create_table(
        "run_task_state_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("definition_task_id", sa.Uuid(), nullable=False),
        sa.Column("task_execution_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "old_status",
            sa.Enum(
                "PENDING", "RUNNING", "COMPLETED", "FAILED", "SKIPPED", name="taskexecutionstatus"
            ),
            nullable=True,
        ),
        sa.Column(
            "new_status",
            sa.Enum(
                "PENDING", "RUNNING", "COMPLETED", "FAILED", "SKIPPED", name="taskexecutionstatus"
            ),
            nullable=False,
        ),
        sa.Column("event_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["definition_task_id"],
            ["experiment_definition_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_execution_id"],
            ["run_task_executions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_run_task_state_events_definition_task_id"),
        "run_task_state_events",
        ["definition_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_run_task_state_events_event_type"),
        "run_task_state_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_run_task_state_events_run_id"), "run_task_state_events", ["run_id"], unique=False
    )
    op.create_table(
        "thread_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("thread_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("task_execution_id", sa.Uuid(), nullable=True),
        sa.Column("from_agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("to_agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sequence_num", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_execution_id"],
            ["run_task_executions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_thread_messages_run_id"), "thread_messages", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_thread_messages_task_execution_id"),
        "thread_messages",
        ["task_execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_thread_messages_thread_id"), "thread_messages", ["thread_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_thread_messages_thread_id"), table_name="thread_messages")
    op.drop_index(op.f("ix_thread_messages_task_execution_id"), table_name="thread_messages")
    op.drop_index(op.f("ix_thread_messages_run_id"), table_name="thread_messages")
    op.drop_table("thread_messages")
    op.drop_index(op.f("ix_run_task_state_events_run_id"), table_name="run_task_state_events")
    op.drop_index(op.f("ix_run_task_state_events_event_type"), table_name="run_task_state_events")
    op.drop_index(
        op.f("ix_run_task_state_events_definition_task_id"), table_name="run_task_state_events"
    )
    op.drop_table("run_task_state_events")
    op.drop_index(op.f("ix_run_resources_run_id"), table_name="run_resources")
    op.drop_table("run_resources")
    op.drop_index(
        op.f("ix_run_generation_turns_worker_binding_key"), table_name="run_generation_turns"
    )
    op.drop_index(
        op.f("ix_run_generation_turns_task_execution_id"), table_name="run_generation_turns"
    )
    op.drop_index(op.f("ix_run_generation_turns_run_id"), table_name="run_generation_turns")
    op.drop_index(
        op.f("ix_run_generation_turns_execution_outcome"), table_name="run_generation_turns"
    )
    op.drop_table("run_generation_turns")
    op.drop_index(op.f("ix_run_actions_task_execution_id"), table_name="run_actions")
    op.drop_index(op.f("ix_run_actions_run_id"), table_name="run_actions")
    op.drop_table("run_actions")
    op.drop_index(op.f("ix_run_task_executions_status"), table_name="run_task_executions")
    op.drop_index(op.f("ix_run_task_executions_run_id"), table_name="run_task_executions")
    op.drop_index(op.f("ix_run_task_executions_node_id"), table_name="run_task_executions")
    op.drop_index(
        op.f("ix_run_task_executions_definition_worker_id"), table_name="run_task_executions"
    )
    op.drop_index(
        op.f("ix_run_task_executions_definition_task_id"), table_name="run_task_executions"
    )
    op.drop_table("run_task_executions")
    op.drop_index(op.f("ix_run_graph_edges_target_node_id"), table_name="run_graph_edges")
    op.drop_index(op.f("ix_run_graph_edges_status"), table_name="run_graph_edges")
    op.drop_index(op.f("ix_run_graph_edges_source_node_id"), table_name="run_graph_edges")
    op.drop_index(op.f("ix_run_graph_edges_run_id"), table_name="run_graph_edges")
    op.drop_table("run_graph_edges")
    op.drop_index(op.f("ix_run_task_evaluations_run_id"), table_name="run_task_evaluations")
    op.drop_index(
        op.f("ix_run_task_evaluations_definition_task_id"), table_name="run_task_evaluations"
    )
    op.drop_index(
        op.f("ix_run_task_evaluations_definition_evaluator_id"), table_name="run_task_evaluations"
    )
    op.drop_table("run_task_evaluations")
    op.drop_index(op.f("ix_run_graph_nodes_task_key"), table_name="run_graph_nodes")
    op.drop_index(op.f("ix_run_graph_nodes_status"), table_name="run_graph_nodes")
    op.drop_index(op.f("ix_run_graph_nodes_run_id"), table_name="run_graph_nodes")
    op.drop_table("run_graph_nodes")
    op.drop_index(
        op.f("ix_experiment_definition_task_evaluators_task_id"),
        table_name="experiment_definition_task_evaluators",
    )
    op.drop_index(
        op.f("ix_experiment_definition_task_evaluators_experiment_definition_id"),
        table_name="experiment_definition_task_evaluators",
    )
    op.drop_index(
        op.f("ix_experiment_definition_task_evaluators_evaluator_binding_key"),
        table_name="experiment_definition_task_evaluators",
    )
    op.drop_table("experiment_definition_task_evaluators")
    op.drop_index(
        op.f("ix_experiment_definition_task_dependencies_task_id"),
        table_name="experiment_definition_task_dependencies",
    )
    op.drop_index(
        op.f("ix_experiment_definition_task_dependencies_experiment_definition_id"),
        table_name="experiment_definition_task_dependencies",
    )
    op.drop_index(
        op.f("ix_experiment_definition_task_dependencies_depends_on_task_id"),
        table_name="experiment_definition_task_dependencies",
    )
    op.drop_table("experiment_definition_task_dependencies")
    op.drop_index(
        op.f("ix_experiment_definition_task_assignments_worker_binding_key"),
        table_name="experiment_definition_task_assignments",
    )
    op.drop_index(
        op.f("ix_experiment_definition_task_assignments_task_id"),
        table_name="experiment_definition_task_assignments",
    )
    op.drop_index(
        op.f("ix_experiment_definition_task_assignments_experiment_definition_id"),
        table_name="experiment_definition_task_assignments",
    )
    op.drop_table("experiment_definition_task_assignments")
    op.drop_index(op.f("ix_training_metrics_session_id"), table_name="training_metrics")
    op.drop_table("training_metrics")
    op.drop_index(op.f("ix_threads_run_id"), table_name="threads")
    op.drop_index(op.f("ix_threads_agent_b_id"), table_name="threads")
    op.drop_index(op.f("ix_threads_agent_a_id"), table_name="threads")
    op.drop_table("threads")
    op.drop_index(op.f("ix_run_graph_mutations_target_id"), table_name="run_graph_mutations")
    op.drop_index(op.f("ix_run_graph_mutations_sequence"), table_name="run_graph_mutations")
    op.drop_index(op.f("ix_run_graph_mutations_run_id"), table_name="run_graph_mutations")
    op.drop_index(op.f("ix_run_graph_mutations_mutation_type"), table_name="run_graph_mutations")
    op.drop_table("run_graph_mutations")
    op.drop_index(op.f("ix_run_graph_annotations_sequence"), table_name="run_graph_annotations")
    op.drop_index(op.f("ix_run_graph_annotations_run_id"), table_name="run_graph_annotations")
    op.drop_index("ix_annotation_lookup", table_name="run_graph_annotations")
    op.drop_table("run_graph_annotations")
    op.drop_index(op.f("ix_rollout_batch_runs_run_id"), table_name="rollout_batch_runs")
    op.drop_index(op.f("ix_rollout_batch_runs_batch_id"), table_name="rollout_batch_runs")
    op.drop_table("rollout_batch_runs")
    op.drop_index(
        op.f("ix_experiment_definition_tasks_task_key"), table_name="experiment_definition_tasks"
    )
    op.drop_index(
        op.f("ix_experiment_definition_tasks_instance_id"), table_name="experiment_definition_tasks"
    )
    op.drop_index(
        op.f("ix_experiment_definition_tasks_experiment_definition_id"),
        table_name="experiment_definition_tasks",
    )
    op.drop_table("experiment_definition_tasks")
    op.drop_index(op.f("ix_training_sessions_status"), table_name="training_sessions")
    op.drop_index(
        op.f("ix_training_sessions_experiment_definition_id"), table_name="training_sessions"
    )
    op.drop_table("training_sessions")
    op.drop_index(op.f("ix_runs_status"), table_name="runs")
    op.drop_index(op.f("ix_runs_experiment_definition_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_cohort_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_rollout_batches_status"), table_name="rollout_batches")
    op.drop_index(op.f("ix_rollout_batches_definition_id"), table_name="rollout_batches")
    op.drop_table("rollout_batches")
    op.drop_index(
        op.f("ix_experiment_definition_workers_worker_type"),
        table_name="experiment_definition_workers",
    )
    op.drop_index(
        op.f("ix_experiment_definition_workers_experiment_definition_id"),
        table_name="experiment_definition_workers",
    )
    op.drop_index(
        op.f("ix_experiment_definition_workers_binding_key"),
        table_name="experiment_definition_workers",
    )
    op.drop_table("experiment_definition_workers")
    op.drop_index(
        op.f("ix_experiment_definition_instances_instance_key"),
        table_name="experiment_definition_instances",
    )
    op.drop_index(
        op.f("ix_experiment_definition_instances_experiment_definition_id"),
        table_name="experiment_definition_instances",
    )
    op.drop_table("experiment_definition_instances")
    op.drop_index(
        op.f("ix_experiment_definition_evaluators_experiment_definition_id"),
        table_name="experiment_definition_evaluators",
    )
    op.drop_index(
        op.f("ix_experiment_definition_evaluators_evaluator_type"),
        table_name="experiment_definition_evaluators",
    )
    op.drop_index(
        op.f("ix_experiment_definition_evaluators_binding_key"),
        table_name="experiment_definition_evaluators",
    )
    op.drop_table("experiment_definition_evaluators")
    op.drop_index(
        op.f("ix_experiment_cohort_stats_cohort_id"), table_name="experiment_cohort_stats"
    )
    op.drop_table("experiment_cohort_stats")
    op.drop_index(op.f("ix_saved_worker_specs_worker_type"), table_name="saved_worker_specs")
    op.drop_index(op.f("ix_saved_worker_specs_slug"), table_name="saved_worker_specs")
    op.drop_table("saved_worker_specs")
    op.drop_index(
        op.f("ix_saved_experiment_templates_slug"), table_name="saved_experiment_templates"
    )
    op.drop_table("saved_experiment_templates")
    op.drop_index(op.f("ix_saved_evaluator_specs_slug"), table_name="saved_evaluator_specs")
    op.drop_index(
        op.f("ix_saved_evaluator_specs_evaluator_type"), table_name="saved_evaluator_specs"
    )
    op.drop_table("saved_evaluator_specs")
    op.drop_index(op.f("ix_saved_benchmark_specs_slug"), table_name="saved_benchmark_specs")
    op.drop_index(
        op.f("ix_saved_benchmark_specs_benchmark_type"), table_name="saved_benchmark_specs"
    )
    op.drop_table("saved_benchmark_specs")
    op.drop_index(
        op.f("ix_experiment_definitions_benchmark_type"), table_name="experiment_definitions"
    )
    op.drop_table("experiment_definitions")
    op.drop_index(op.f("ix_experiment_cohorts_name"), table_name="experiment_cohorts")
    op.drop_table("experiment_cohorts")
    # ### end Alembic commands ###
